wtx-instances/web-socket-examples/web-socket-concurrent-client.rs, wtx-macros/src/client_api_framework/pkg/data_format.rs, wtx-macros/src/client_api_framework/pkg/sir/sir_final_values.rs, wtx-macros/src/error.rs, wtx-macros/src/from_records.rs, wtx-macros/src/lib.rs, wtx-macros/src/misc.rs, wtx-macros/tests/ui/error_enum/bad_before_sending.stderr, wtx/src/client_api_framework/misc.rs, wtx/src/client_api_framework/pkg.rs, wtx/src/client_api_framework/pkg/batch_pkg.rs, wtx/src/client_api_framework/pkg/pkg_with_helper.rs, wtx/src/database/client/postgres/tys.rs, wtx/src/database/from_records.rs, wtx/src/database/misc.rs, wtx/src/database/record_values.rs, wtx/src/grpc/grpc_middleware.rs, wtx/src/http/mime.rs, wtx/src/http/server_framework/arguments/serde_json.rs, wtx/src/http/server_framework/methods.rs, wtx/src/http/server_framework/res_finalizer.rs, wtx/src/http/server_framework/state.rs, wtx/src/misc.rs, wtx/src/misc/iter_wrapper.rs, wtx/src/misc/wrapper.rs
Adds a new procedural macro that implements the `FromRecords` trait.
=> Introduce a new derive macro

Cargo.lock, wtx/Cargo.toml
=> wtx-0.28.0

wtx-docs/src/database-client/README.md, wtx/src/client_api_framework/api.rs, wtx/src/client_api_framework/network/transport/recieving_transport.rs, wtx/src/client_api_framework/network/transport/sending_receiving_transport.rs, wtx/src/client_api_framework/network/transport/sending_transport.rs, wtx/src/client_api_framework/pkg.rs, wtx/src/database/client/postgres/postgres_executor.rs, wtx/src/database/executor.rs, wtx/src/database/schema_manager.rs, wtx/src/http/optioned_server/http2_tokio.rs, wtx/src/http/optioned_server/web_socket_tokio.rs, wtx/src/http/server_framework/endpoint.rs, wtx/src/http/server_framework/middleware.rs, wtx/src/http/session/session_manager_builder.rs, wtx/src/http/session/session_store.rs, wtx/src/http2.rs, wtx/src/http2/client_stream.rs, wtx/src/http2/common_stream.rs, wtx/src/http2/frame_reader.rs, wtx/src/http2/misc.rs, wtx/src/http2/send_msg.rs, wtx/src/http2/server_stream.rs, wtx/src/misc/fn_fut.rs, wtx/src/misc/lock.rs, wtx/src/misc/stream/stream_reader.rs, wtx/src/misc/stream/stream_writer.rs, wtx/src/pool.rs, wtx/src/pool/resource_manager.rs, wtx/src/pool/simple_pool.rs
In 2024 `Future` is already included in the prelude
=> Remove manual `Future` imports

Cargo.lock, wtx/Cargo.toml
=> wtx-0.29.0

Cargo.lock, wtx-instances/database-examples/database-client-mysql.rs, wtx-macros/src/client_api_framework/api.rs, wtx-macros/src/client_api_framework/pkg/sir/sir_final_values.rs, wtx-macros/tests/ui/pass/custom_transport.rs, wtx/src/client_api_framework.rs, wtx/src/client_api_framework/api.rs, wtx/src/client_api_framework/misc.rs, wtx/src/client_api_framework/network/http.rs, wtx/src/client_api_framework/network/transport.rs, wtx/src/client_api_framework/network/transport/mock.rs, wtx/src/client_api_framework/network/transport/recieving_transport.rs, wtx/src/client_api_framework/network/transport/sending_receiving_transport.rs, wtx/src/client_api_framework/network/transport/sending_transport.rs, wtx/src/client_api_framework/network/transport/unit.rs, wtx/src/client_api_framework/network/transport/wtx_http.rs, wtx/src/client_api_framework/network/transport/wtx_ws.rs, wtx/src/client_api_framework/network/transport/wtx_ws/web_socket.rs, wtx/src/client_api_framework/network/transport/wtx_ws/web_socket_parts_owned.rs, wtx/src/client_api_framework/network/transport/wtx_ws/web_socket_reader_part_owned.rs, wtx/src/client_api_framework/network/transport/wtx_ws/web_socket_writer_part_owned.rs, wtx/src/client_api_framework/send_bytes_ty.rs, wtx/src/http/http_client.rs, wtx/src/misc/facades/arc.rs, wtx/src/misc/single_type_storage.rs, wtx/src/misc/sync/atomic_cell.rs, wtx/src/pool/simple_pool.rs
In some scenarios `AsyncFnOnce` makes a future `!Send`.
=> Remove usage of `AsyncFnOnce`

wtx-docs/src/database-client/encrypted-connections.md, wtx-macros/src/error.rs, wtx-macros/src/from_records.rs, wtx/src/database/from_records.rs, wtx/src/database/misc.rs, wtx/src/http/server_framework/tokio.rs, wtx/src/pool/resource_manager.rs
Removes the `'static` requirement when passing certificates
=> Relax static bounds

Cargo.lock, wtx/Cargo.toml
=> wtx-0.30.0

wtx-docs/src/database-client/encrypted-connections.md, wtx-instances/http-server-framework-examples/http-server-framework-cors.rs, wtx-ui/Cargo.toml, wtx/src/http/server_framework.rs, wtx/src/http/server_framework/cors_middleware.rs
It is not necessary. Such a thing was an oversight.
=> Relax static bounds of the CORS middleware

wtx-docs/src/http2/README.md, wtx-ui/src/clap.rs, wtx-ui/src/schema_manager.rs, wtx/src/database/schema_manager.rs, wtx/src/database/schema_manager/commands/migrate.rs, wtx/src/database/schema_manager/commands/rollback.rs, wtx/src/database/schema_manager/fixed_sql_commands.rs, wtx/src/database/schema_manager/integration_tests.rs, wtx/src/database/schema_manager/integration_tests/db/mysql.rs, wtx/src/database/schema_manager/integration_tests/db/postgres.rs, wtx/src/database/schema_manager/integration_tests/generic.rs, wtx/src/database/schema_manager/integration_tests/schema.rs, wtx/src/database/schema_manager/integration_tests/schema/with_schema.rs, wtx/src/database/schema_manager/integration_tests/schema/without_schema.rs, wtx/src/database/schema_manager/migration/db_migration.rs, wtx/src/database/schema_manager/migration/migration_common.rs, wtx/src/database/schema_manager/migration/migration_group.rs, wtx/src/database/schema_manager/migration/user_migration.rs, wtx/src/database/schema_manager/migration_status.rs, wtx/src/database/schema_manager/misc.rs, wtx/src/database/schema_manager/schema_manager_error.rs, wtx/src/misc/tokio_rustls.rs, wtx/tests/embed-migrations.rs
Useful to understand what happened in a migration operation
=> Return the status of a migration

wtx/src/http/optioned_server/http2_tokio.rs, wtx/src/http/version.rs
The current request log is a bit strange
=> Improve the logging of requests

README.md, wtx-macros/src/client_api_framework/pkg/sir/sir_aux_item_values.rs, wtx/src/client_api_framework/macros.rs, wtx/src/client_api_framework/misc.rs, wtx/src/client_api_framework/network/transport/mock.rs, wtx/src/client_api_framework/network/transport/wtx_http.rs, wtx/src/client_api_framework/network/transport/wtx_ws.rs, wtx/src/client_api_framework/pkg/pkgs_aux.rs, wtx/src/client_api_framework/tests.rs
=> Avoid logging HTTP body contents

wtx-docs/src/error-handling/README.md
=> Fix doc example

.scripts/internal-tests-1.sh, Cargo.lock, wtx-docs/src/error-handling/README.md, wtx-docs/src/time/README.md, wtx-ui/Cargo.toml, wtx/Cargo.toml
=> wtx 0.32.0

Cargo.lock, wtx-docs/src/SUMMARY.md, wtx-docs/src/error-handling/README.md, wtx-docs/src/internal-development/README.md, wtx-fuzz/Cargo.toml, wtx-fuzz/deque.rs, wtx/Cargo.toml, wtx/src/collection/blocks_deque.rs, wtx/src/collection/blocks_deque/blocks_deque_builder.rs, wtx/src/collection/deque.rs, wtx/src/collection/deque/tests.rs, wtx/src/collection/deque/tests/extend_front_from_copyable_within.rs, wtx/src/collection/vector.rs, wtx/src/database/client/mysql/mysql_executor/fetch.rs, wtx/src/database/client/mysql/mysql_protocol/binary_row_res.rs, wtx/src/database/client/mysql/mysql_protocol/lenenc_content.rs, wtx/src/database/client/mysql/mysql_protocol/text_row_res.rs, wtx/src/database/client/mysql/tys.rs, wtx/src/database/client/mysql/tys/chrono.rs, wtx/src/database/client/mysql/tys/time.rs, wtx/src/http2/hpack_decoder.rs, wtx/src/http2/hpack_encoder.rs, wtx/src/http2/hpack_headers.rs, wtx/src/misc/usize.rs, wtx/src/rng/from_rng.rs
=> Add new `extend_front_from_copyable_within` method

README.md, wtx-fuzz/Cargo.toml, wtx-fuzz/date_time.rs, wtx-fuzz/deque.rs, wtx/src/collection/deque.rs, wtx/src/http/cookie.rs, wtx/src/http/cookie/cookie_generic.rs, wtx/src/http/cookie/cookie_str.rs, wtx/src/http/session/session_manager.rs, wtx/src/http/session/session_manager_builder.rs, wtx/src/http/session/session_middleware.rs, wtx/src/http/session/session_state.rs, wtx/src/misc/num_array.rs, wtx/src/time.rs, wtx/src/time/date.rs, wtx/src/time/date_time.rs, wtx/src/time/date_time/format.rs, wtx/src/time/month.rs, wtx/src/time/time_error.rs, wtx/src/time/weekday.rs, wtx/src/time/year.rs
One step closer to a full implementation.
=> Add formatting options for DateTime

README.md, wtx-docs/src/internal-development/README.md, wtx/src/time/date_time.rs, wtx/src/time/date_time/format.rs
Also correctly handles `serde`
=> Add more formatting options for DateTime

.scripts/integration-tests-mysql.sh, wtx-macros/Cargo.toml, wtx-macros/src/from_records.rs, wtx-macros/tests/ui/pass/from_records.rs, wtx/src/calendar/date_time.rs, wtx/src/calendar/time.rs, wtx/src/http/session/session_manager.rs, wtx/src/http/session/session_middleware.rs
=> Add new `trunc_to_sec` method

wtx-macros/src/client_api_framework/pkg/data_format.rs, wtx/src/calendar.rs, wtx/src/calendar/date.rs, wtx/src/calendar/date/format.rs, wtx/src/calendar/date_time.rs, wtx/src/calendar/date_time/format.rs, wtx/src/calendar/date_time/tests.rs, wtx/src/calendar/format.rs, wtx/src/calendar/format/calendar_token.rs, wtx/src/calendar/format/parsed_data.rs, wtx/src/calendar/time.rs, wtx/src/calendar/time/format.rs, wtx/src/http/cookie.rs
The macro was issuing double-double quotes
=> Fix JsonRpc string

wtx/src/http/server_framework.rs, wtx/src/http/server_framework/arguments/serde_json.rs, wtx/src/http/server_framework/body_clean.rs, wtx/src/http/server_framework/headers_clean.rs, wtx/src/http/server_framework/params_clean.rs, wtx/src/http/server_framework/res_finalizer.rs, wtx/src/http/status_code.rs
Useful to avoid duplicated code
=> Add more `ResFinalizer` impls

wtx-instances/http-server-framework-examples/http-server-framework.rs, wtx/src/http/server_framework.rs, wtx/src/http/server_framework/methods.rs, wtx/src/http/server_framework/methods/delete.rs, wtx/src/http/server_framework/methods/json.rs, wtx/src/http/server_framework/methods/patch.rs, wtx/src/http/server_framework/methods/post.rs, wtx/src/http/server_framework/methods/put.rs
`GET` and `POST` were the only available wrappers but now `PUT`, `POST` and `DELETE` are also available.
=> Add remaining method wrappers

Cargo.lock, wtx-ui/Cargo.toml, wtx/Cargo.toml
=> wtx-0.34-0

Cargo.lock, README.md, wtx-ui/Cargo.toml, wtx/Cargo.toml, wtx/src/http/headers.rs, wtx/src/http/req_res_builder.rs
=> wtx-0.35.0

wtx-instances/src/bin/autobahn-client-concurrent.rs, wtx-instances/web-socket-examples/web-socket-client-concurrent-channel.rs, wtx-instances/web-socket-examples/web-socket-client-concurrent-mutex.rs, wtx-instances/web-socket-examples/web-socket-client-concurrent.rs, wtx/src/client_api_framework/network/transport/wtx_ws/web_socket_parts_owned.rs, wtx/src/client_api_framework/network/transport/wtx_ws/web_socket_reader_part_owned.rs, wtx/src/client_api_framework/network/transport/wtx_ws/web_socket_writer_part_owned.rs, wtx/src/http2/web_socket_over_stream.rs, wtx/src/web_socket.rs, wtx/src/web_socket/web_socket_parts.rs, wtx/src/web_socket/web_socket_parts/web_socket_generic.rs, wtx/src/web_socket/web_socket_parts/web_socket_mut.rs, wtx/src/web_socket/web_socket_parts/web_socket_owned.rs, wtx/src/web_socket/web_socket_reader.rs, wtx/src/web_socket/web_socket_replier.rs
=> Rename WebSocket structures

wtx/src/collection/try_extend.rs
=> Add more `TryExtend` implementations

.github/workflows/bencher.yaml, .github/workflows/docs.yaml, .github/workflows/tests.yaml, Cargo.lock, wtx-macros/Cargo.toml, wtx-ui/Cargo.toml, wtx/Cargo.toml, wtx/src/collection/vector.rs
=> Bump versions

wtx/src/database/client/mysql/mysql_record.rs, wtx/src/database/client/postgres/postgres_record.rs, wtx/src/database/client/rdbms/common_record.rs, wtx/src/database/database_error.rs, wtx/src/database/misc.rs, wtx/src/database/record.rs, wtx/src/database/value_ident.rs, wtx/src/web_socket.rs, wtx/src/web_socket/handshake/tests.rs, wtx/src/web_socket/misc.rs, wtx/src/web_socket/web_socket_error.rs, wtx/src/web_socket/web_socket_reader.rs
=> Add `Copy` bound for `ValueIdent`

.github/workflows/tests.yaml, Cargo.lock, wtx-docs/src/calendar/README.md, wtx/Cargo.toml, wtx/src/http/session/session_middleware.rs
=> Updates dependencies

wtx-fuzz/web_socket.rs, wtx/src/misc/mem.rs, wtx/src/misc/secret.rs, wtx/src/rng/xorshift.rs, wtx/src/stream/std.rs, wtx/src/stream/stream_with_tls.rs, wtx/src/stream/tokio.rs, wtx/src/sync.rs, wtx/src/sync/fence.rs, wtx/src/sync/seq_lock.rs, wtx/src/web_socket.rs, wtx/src/web_socket/handshake.rs
=> Implement Stream traits for UnixStream
